# Generated by Django 3.1.7 on 2021-03-06 10:41

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="ApiRequest",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("request_id", models.CharField(max_length=50, unique=True)),
                ("path_coordinates", models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name="ApiRequestResult",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("calculations_start", models.DateTimeField()),
                ("calculations_end", models.DateTimeField()),
                (
                    "api_request",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="api",
                        to="total_distance.apirequest",
                    ),
                ),
            ],
        ),
    ]
