# Generated by Django 3.1.7 on 2021-03-08 00:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("total_distance", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="apirequest",
            name="calculations_end",
            field=models.DateTimeField(null=True),
        ),
        migrations.AlterField(
            model_name="apirequest",
            name="calculations_start",
            field=models.DateTimeField(null=True),
        ),
    ]
